name: Test
on:
  milestone:
    types: [closed]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Create a release draft for a milestone
        id: create-release-milestone
        uses: ecampidoglio/auto-release-milestone@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
